### PR TITLE
Next deploy refactor

### PR DESCRIPTION
**Pull request by denciu**
Changes:
- extended typescript support via `typechain -> ethers`
- deploy has been separated into script per contract and connected via dependencies and tags
- deployments are now saved to `deployments` folder per each network
- automatic contract verification during deployment also to blockscout (via sourcify)
- updated packages

### CODE REVIEW

**Review by nicoelzer — APPROVED** [review]

**Comment by nicoelzer** [comment]
Great work @denciu – looks good to me!

**Comment by denciu** [comment]
> Great work @denciu – looks good to me!

Awwww <3

**Comment by adamazad** [comment]
Can we fit in more changes? 🙂 #112 #108

**Comment by denciu** [comment]
> Can we fit in more changes?  #112 #108

Wanted to apply these changes in separate branch but feel free :)

**Pull request merged**
